name: simple_tv_navigation_example
description: Example app for Simple TV Navigation package

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  simple_tv_navigation:
    path: ../
  provider: ^6.1.1  
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true 